#version: "3.8"
#
services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    user: root     # 👈 add this
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml
      - ./loki/data:/var/lib/loki
    command: -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
      - ./promtail/data:/var/lib/promtail
      - /var/log:/var/log:ro
      - ./nginx/log:/saad-nginx-logs:ro           # 👈 changed mount path
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki
      - nginx

#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    user: "472"
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./grafana/data:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    depends_on:
#      - loki

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx    # 👈 changed mount path
    restart: always

