events {}

http {
    server {
        listen 80;
        server_name localhost;

        access_log /custom-logs/access.log;
        error_log  /custom-logs/error.log;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }
}

